- hosts: hypershift1
  gather_facts: false
  collections:
    - community.general
  vars:
    resetType: Status
    validResetTypes:
      - Status
      - "On"
      - ForceOff
      - ForceRestart
      - GracefulShutdown
      - PushPowerButton
      - NMI
  tasks:
    - when: resetType|default("") not in validResetTypes
      run_once: true
      fail:
        msg: |-
          `resetType` must be set to one of {{ validResetTypes|join(", ") }}

    - when: resetType == "Status"
      block:
      - name: Get system information
        delegate_to: localhost
        uri:
          url: "{{ redfishBaseURL }}{{ redfishSystemEndpoint }}"
          url_username: "{{ bmcUsername }}"
          url_password: "{{ bmcPassword }}"
          validate_certs: false
          force_basic_auth: true
        register: system

      - name: Display power state
        debug:
          msg: "Power state: {{ system.json.PowerState }}"

    - when: resetType != "Status"
      block:
      - name: Perform power action ({{ resetType }})
        delegate_to: localhost
        ignore_errors: true
        uri:
          url: "{{ redfishBaseURL }}{{ redfishComputerSystemResetAction }}"
          method: POST
          body_format: json
          body:
            ResetType: "{{ resetType }}"
          url_username: root
          url_password: "{{ bmcPassword }}"
          validate_certs: false
          status_code:
            - 200
            - 204
        register: power

      - name: Report errors
        when: power is failed
        block:
          - debug:
              msg: "{{ power.json }}"

          - fail:
